@TM:1398795842
@N:  :"":0:0:0:-1|Running in 64-bit mode
@TM:1398795849
@N: BW106 :"":0:0:0:-1|Synplicity Constraint File capacitance units using default value of 1pF 
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF666 :"":0:0:0:-1|Clock conversion enabled 
@N: MF666 :"":0:0:0:-1|Clock conversion enabled 
@N: MT206 :"":0:0:0:-1|Auto Constrain mode is enabled
@N: MT320 :"":0:0:0:-1|Timing report estimates place and route data. Please look at the place and route timing report for final timing.
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock.
@TM:1398795937
@W: MT420 :"":0:0:0:-1|Found inferred clock count_down_timer|clk with period 8.58ns. Please declare a user-defined clock on object "p:clk"
@TM:1398795842
@N: CD720 :"C:\Synopsys\fpga_G201209SP1\lib\vhd\std.vhd":123:18:123:21|M
@N:  :"H:\ese382\lab10s14\setable_timer\src\count_down_timer.vhd":28:7:28:22|M
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\count_down_timer.vhd":28:7:28:22|M
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\fsm.vhd":5:7:5:18|M
@N: CD231 :"H:\ese382\lab10s14\setable_timer\src\fsm.vhd":16:12:16:13|M
@N: CL201 :"H:\ese382\lab10s14\setable_timer\src\fsm.vhd":21:2:21:3|M
@TM:1398795937
@N: FX271 :"h:\ese382\lab10s14\setable_timer\src\fsm.vhd":33:3:33:13|M
@TM:1398795849
@N: FX271 :"h:\ese382\lab10s14\setable_timer\src\fsm.vhd":34:3:34:12|M
@N: FX271 :"h:\ese382\lab10s14\setable_timer\src\fsm.vhd":35:3:35:12|M
@TM:1398795842
@W: CD604 :"H:\ese382\lab10s14\setable_timer\src\fsm.vhd":38:3:38:15|M
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\minutes_counter.vhd":29:7:29:21|M
@TM:1398795930
@W: CL169 :"H:\ese382\lab10s14\setable_timer\src\minutes_counter.vhd":53:2:53:3|M
@TM:1398795842
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\pedgefsm.vhd":28:7:28:14|M
@N: CD233 :"H:\ese382\lab10s14\setable_timer\src\pedgefsm.vhd":38:12:38:13|M
@N: CL201 :"H:\ese382\lab10s14\setable_timer\src\pedgefsm.vhd":43:2:43:3|M
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":28:7:28:32|M
@N: CD233 :"H:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":43:11:43:12|M
@N: CL201 :"H:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":49:2:49:3|M
@TM:1398795849
@N: FX271 :"h:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":49:2:49:3|M
@TM:1398795845
@W: MT529 :"h:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":49:2:49:3|M
@TM:1398795842
@W: CD604 :"H:\ese382\lab10s14\setable_timer\src\rotary_encoder_decoder_fsm.vhd":66:4:66:16|M
@N: CD630 :"H:\ese382\lab10s14\setable_timer\src\seconds_counter.vhd":10:7:10:21|M
@TM:1398795849
@N: FX271 :"h:\ese382\lab10s14\setable_timer\src\seconds_counter.vhd":30:2:30:3|M
